#!/usr/bin/env php

<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use RoverChallenge\Core;

$rover = new Application();

$rover->add(new Core());

$rover->run();